DOCKER_IMAGE_OWNER = 'habibiefaried'
DOCKER_IMAGE_NAME = 'free5gc'
DOCKER_IMAGE_TAG = 'base'

.PHONY: base
base:
	docker build -t ${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ./base
	docker image ls ${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
