apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    role: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: db
    spec:
      containers:
      - image: mongo
        name: db
        env:
        - name: MONGO_INITDB_DATABASE
          value: free5gc
        args:
        - --dbpath=/data/db
        - --port=27017
        - --bind_ip=0.0.0.0
        command:
        - mongod
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "512Mi"
        ports:
        - containerPort: 27017
          protocol: TCP
---
---
apiVersion: v1
kind: Service
metadata:
 name: db
 labels:
  name: db
spec:
 ports:
  - port: 27017
    targetPort: 27017
 type: NodePort
 selector:
  role: db
